// app/layout.js
import { Poppins } from "next/font/google";
import "./globals.css";

// Import Poppins sebagai font utama
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Sesuaikan kebutuhan
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
